### PR TITLE
Materializing things

### PR DESCRIPTION
**Pull request by S00185883**

### CODE REVIEW

**Comment by S00185883** [comment]
Screenshot 2021-08-04 at 15 40 42

**Comment by eim-ostk** [comment]
image

Seems to work well!

I'd have "Office Re-entry Requirements" in a similar format as the native Materialize example -- same for the close Button -- they should be built in from the example.

I'd also remove the white box within the grey box look -- and reduce the line-height of the text (they're very far spaced out)

Also, hovering anywhere over the modal makes the cursor become "pointer" -- I'd have it as "default" (css thing)

**Comment by eim-ostk** [comment]
Have another look at the Figma also -- I'd have the numbers be bigger

**Comment by eim-ostk** [comment]
I would recommend making the Modal Component be re-usable, because we'll have to use it throughout the app. Make it generic so that you can then pass the contents down to the modal as props

**Review by S00189802 — APPROVED** [review]

**Review by S00189591 — APPROVED** [review]
LGTM

**Pull request merged**
